import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BubbleBg from "@/components/BubbleBg";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Content Generator",
  description: "Generated by UNIDATA",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>{}</head>
      <body className="relative">
        <BubbleBg />
        <Header />

        {children}
      </body>
    </html>
  );
}
